---
resources:
- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/kubo-ci
    branch: master

- name: git-kubo-deployment
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-deployment.git
    branch: develop
    private_key: ((git-ssh-key.private_key))

- name: git-cfcr-etcd-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: cfcr-etcd-release
    access_token: ((github-token-key))

- name: boshdns-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh-dns-release

- name: bpm-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/bpm-release

- name: docker-boshrelease
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: docker-boshrelease
    access_token: ((github-token-key))

jobs:
- name: bump-boshdns-release
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: boshdns-release
      trigger: true
  - task: bump-boshrelease
    file: git-kubo-ci/tasks/bump-boshrelease.yml
    input_mapping:
      boshrelease: boshdns-release
    params:
      RELEASE_NAME: bosh-dns
  - put: git-kubo-deployment
    params:
      repository: git-kubo-deployment-output

- name: bump-bpm-release
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: bpm-release
      trigger: true
  - task: bump-boshrelease
    file: git-kubo-ci/tasks/bump-boshrelease.yml
    input_mapping:
      boshrelease: bpm-release
    params:
      RELEASE_NAME: bpm
  - put: git-kubo-deployment
    params:
      repository: git-kubo-deployment-output

- name: bump-etcd-release
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: git-cfcr-etcd-release
      trigger: true
  - task: bump-etcd-release
    file: git-kubo-ci/tasks/bump-boshrelease.yml
    input_mapping:
       boshrelease: git-cfcr-etcd-release
    params:
      RELEASE_NAME: cfcr-etcd
      REPO_URL: https://github.com/cloudfoundry-incubator/cfcr-etcd-release
  - put: git-kubo-deployment
    params:
      repository: git-kubo-deployment-output

- name: bump-docker-boshrelease
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: docker-boshrelease
      trigger: true
  - task: bump-kubo-docker
    file: git-kubo-ci/tasks/bump-boshrelease.yml
    input_mapping:
      boshrelease: docker-boshrelease
    params:
      RELEASE_NAME: docker
      REPO_URL: https://github.com/cloudfoundry-incubator/docker-boshrelease
  - put: git-kubo-deployment
    params:
      repository: git-kubo-deployment-output
