---
resources:
- name: docker-boshrelease
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: docker-boshrelease
    access_token: ((github-token-key))

- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/kubo-ci
    branch: master

- name: git-kubo-deployment
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-deployment.git
    branch: develop
    private_key: ((git-ssh-key.private_key))

jobs:
- name: bump-kubo-docker-boshrelease
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: docker-boshrelease
      trigger: true
  - task: bump-kubo-docker
    file: git-kubo-ci/tasks/bump-boshrelease.yml
    input_mapping:
      boshrelease: docker-boshrelease
    params:
      RELEASE_NAME: docker
      REPO_URL: https://github.com/cloudfoundry-incubator/docker-boshrelease
  - put: git-kubo-deployment
    params:
      repository: git-kubo-deployment-output
